IF EXISTS (SELECT PRIMARY_KEY_VARIABLE FROM TABLE_NAME_VARIABLE WHERE PRIMARY_KEY_VARIABLE ='COMPUTER_DNS_HOSTNAME_VARIABLE') 
BEGIN

SELECT TOP(1) *
INTO #Temp_TABLE_TEMPORARY_NAME_VARIABLE FROM TABLE_NAME_VARIABLE
WHERE PRIMARY_KEY_VARIABLE = 'COMPUTER_DNS_HOSTNAME_VARIABLE'

UPDATE_QUERY_BLOCK_VARIABLE

IF (
    SELECT 
        COUNT(*) 
    FROM (
        SELECT 
            COLUMNS_TO_COMPARE_DURING_UPDATE_VARIABLE
        FROM #Temp_TABLE_TEMPORARY_NAME_VARIABLE

    UNION

        SELECT 
            COLUMNS_TO_COMPARE_DURING_UPDATE_VARIABLE
        FROM TABLE_NAME_VARIABLE
        WHERE PRIMARY_KEY_VARIABLE = 'COMPUTER_DNS_HOSTNAME_VARIABLE') a
    ) > 1
BEGIN

INSERT INTO ChangeLog_TABLE_NAME_VARIABLE
SELECT NEWID() AS 'ID',
*
FROM #Temp_TABLE_TEMPORARY_NAME_VARIABLE

END


DROP TABLE #Temp_TABLE_TEMPORARY_NAME_VARIABLE

END
ELSE
BEGIN

INSERT_QUERY_BLOCK_VARIABLE


END
