IF EXISTS (SELECT PRIMARY_KEY_VARIABLE FROM TABLE_NAME_VARIABLE WHERE PRIMARY_KEY_VARIABLE ='COMPUTER_DNS_HOSTNAME_VARIABLE') 
BEGIN

UPDATE_QUERY_BLOCK_VARIABLE

END
ELSE
BEGIN

INSERT_QUERY_BLOCK_VARIABLE

END
