{
 "title": "Network SpeedTest",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Ping Latency ms",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \nTimeStamp AS 'time',\nPing_Latency_ms AS 'Latency ms'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "Ping Jitter ms",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \nTimeStamp AS 'time',\nPing_jitter_ms AS 'Jitter ms'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "Download Speed Mbps",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \nTimeStamp AS 'time',\nDownload_Speed_Mbps AS 'Download Mbps'\nFROM Device_Monitoring.dbo.Event_SpeedTest "
    }
   ]
  },
  {
   "title": "Upload Speed Mbps",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \nTimeStamp AS 'time',\nUpload_Speed_Mbps AS 'Upload Mbps'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \nTimeStamp AS 'time',\nPacketLoss_Percentage AS 'Packet Loss'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "Internet speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \n[TimeStamp] AS 'time',\nDownload_Speed_Mbps AS 'Download Mbps',\nUpload_Speed_Mbps AS 'Upload Mbps'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT\n[TimeStamp] AS 'time',\nPing_Latency_ms AS 'Ping Latency',\nDownload_Latency_High_ms AS 'Download Latency ms',\nUpload_Latency_High_ms AS 'Upload Latency ms'\nFROM Device_Monitoring.dbo.Event_SpeedTest"
    }
   ]
  },
  {
   "title": "48h Tests",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT TOP(48)\n  DATEADD(HOUR,-1,[TimeStamp]) AS 'Measurement time',\n  Download_Speed_Mbps AS 'Download',\n  Upload_Speed_Mbps AS 'Upload',\n  SpeedTest_Server_Name AS 'Server',\n  URL AS 'Results URL'\nFROM Device_Monitoring.dbo.Event_SpeedTest \nORDER BY TimeStamp DESC"
    }
   ]
  }
 ]
}