{
 "title": "Server Core",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT TOP(1)\nCPU_Temperature_Max \nFROM Device_Monitoring.dbo.Event_PowerAndTemperature \nWHERE DNSHostName = 'Server-Core.Horna.local'\nORDER BY TimeStamp DESC"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT TOP(1)\n  CPU_Load_Percentage\nFROM Device_Monitoring.dbo.Event_ResourceConsumption \nWHERE DNSHostName = 'Server-Core.Horna.local'\nORDER BY TimeStamp DESC"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT TOP(1)\n  RAM_Usage_Percentage\nFROM Device_Monitoring.dbo.Event_ResourceConsumption \nWHERE DNSHostName = 'Server-Core.Horna.local'\nORDER BY TimeStamp DESC"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT TOP(1)\n  Disk_Time_Percentage\nFROM Device_Monitoring.dbo.Event_ResourceConsumption \nWHERE DNSHostName = 'Server-Core.Horna.local'\nORDER BY TimeStamp DESC"
    }
   ]
  },
  {
   "title": "Power W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \n[TimeStamp] AS 'time',\nPowerConsumption_Max AS 'Power W'\nFROM Device_Monitoring.dbo.Event_PowerAndTemperature \nWHERE DNSHostName = 'Server-Core.Horna.local'"
    }
   ]
  },
  {
   "title": "CPU Temperature C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \n  [TimeStamp] AS 'time',\n  CPU_Temperature_Max AS 'CPU Temperature C'\nFROM Device_Monitoring.dbo.Event_PowerAndTemperature \nWHERE DNSHostName = 'Server-Core.Horna.local'"
    }
   ]
  },
  {
   "title": "CPU, RAM, Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT \n[TimeStamp] AS 'time',\nCPU_Load_Percentage AS 'CPU Load',\nRAM_Usage_Percentage AS 'RAM Load',\nDisk_Time_Percentage AS 'Disk Load'\nFROM Device_Monitoring.dbo.Event_ResourceConsumption \nWHERE DNSHostName = 'Server-Core.Horna.local'"
    }
   ]
  },
  {
   "title": "Network Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "Device_Monitoring",
     "rawSql": "SELECT\n[TimeStamp] AS 'time',\nNIC_Received_MBps AS 'Received Mbps',\nNIC_Sent_Mbps AS 'Sent Mbps'\nFROM Device_Monitoring.dbo.Event_ResourceConsumption \nWHERE DNSHostName = 'Server-Core.Horna.local'"
    }
   ]
  }
 ]
}