/*
    .DESCRIPTION
        Query to create Device_Monitoring_Maintenance Database on Microsoft SQL Server.
        This DB is used to collect and store additional information related to scripts execution

        This file was generated by DBeaver.

    .INPUTS
        None

    .OUTPUTS
        None

    .NOTES

        Version:            1.0
        Author:             Stanisław Horna
        Mail:               stanislawhorna@outlook.com
        GitHub Repository:  https://github.com/StanislawHornaGitHub/MonitorWindowsDomainDevices
        Creation Date:      24-Oct-2023
        ChangeLog:

        Date            Who                     What

*/
-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- Device_Monitoring_Maintenance.dbo.LastExecution definition

-- Drop table

-- DROP TABLE Device_Monitoring_Maintenance.dbo.LastExecution;

CREATE TABLE LastExecution (
	Name nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	[Type] nvarchar(50) COLLATE Polish_CI_AS NULL,
	Refresh_Interval_in_seconds int NULL,
	Last_Start_Time datetime NULL,
	AVG_Processing_Duration_ms int NULL,
	Last_Exit_Code int NULL,
	Errors nvarchar(500) COLLATE Polish_CI_AS NULL,
	CONSTRAINT PK_LastExecution PRIMARY KEY (Name)
);


-- Device_Monitoring_Maintenance.dbo.Log_Job definition

-- Drop table

-- DROP TABLE Device_Monitoring_Maintenance.dbo.Log_Job;

CREATE TABLE Log_Job (
	Script_name nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	Start_time datetime NULL,
	End_time datetime NULL,
	Duration time NULL,
	Exit_code int NULL,
	Processed_devices int NULL,
	Message nvarchar(2000) COLLATE Polish_CI_AS NULL
);


-- Device_Monitoring_Maintenance.dbo.Log_Process_coordinator definition

-- Drop table

-- DROP TABLE Device_Monitoring_Maintenance.dbo.Log_Process_coordinator;

CREATE TABLE Log_Process_coordinator (
	[Timestamp] datetime NOT NULL,
	Hostname nvarchar(50) COLLATE Polish_CI_AS NULL,
	PID int NULL,
	Message_type nvarchar(50) COLLATE Polish_CI_AS NULL,
	Message nvarchar(1000) COLLATE Polish_CI_AS NULL
);