/*
    .DESCRIPTION
        Query to create Device_Monitoring Database on Microsoft SQL Server.
        This is main DB used in MonitorWindowsDomainDevices solution,
        to store and compute collected data.

        This file was generated by DBeaver.

    .INPUTS
        None

    .OUTPUTS
        None

    .NOTES

        Version:            1.0
        Author:             Stanisław Horna
        Mail:               stanislawhorna@outlook.com
        GitHub Repository:  https://github.com/StanislawHornaGitHub/MonitorWindowsDomainDevices
        Creation Date:      24-Oct-2023
        ChangeLog:

        Date            Who                     What

*/
-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- Device_Monitoring.dbo.ChangeLog_Object_Hardware definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Hardware;

CREATE TABLE ChangeLog_Object_Hardware (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NOT NULL,
	LastUpdate datetime2 NULL,
	DeviceManufacturer nvarchar(50) COLLATE Polish_CI_AS NULL,
	DeviceModel nvarchar(50) COLLATE Polish_CI_AS NULL,
	NumberOfCPUs tinyint NULL,
	CPUmodel nvarchar(100) COLLATE Polish_CI_AS NULL,
	NumberOfCores tinyint NULL,
	NumberOfLogicalProcessors tinyint NULL,
	NumberOfRAMBanks tinyint NULL,
	RAMCapacity_GB tinyint NULL,
	RAMSpeed_MHz nvarchar(50) COLLATE Polish_CI_AS NULL,
	RAMmanufacturer nvarchar(50) COLLATE Polish_CI_AS NULL,
	GPU_Model nvarchar(100) COLLATE Polish_CI_AS NULL,
	DiskName nvarchar(100) COLLATE Polish_CI_AS NULL,
	StorageCapacity_GB smallint NULL,
	CONSTRAINT PK_ChangeLog_Hardware PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_HardDrives definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_HardDrives;

CREATE TABLE ChangeLog_Object_Hyper_V_HardDrives (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	VMName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ControllerType nvarchar(50) COLLATE Polish_CI_AS NULL,
	VhdFormat nvarchar(50) COLLATE Polish_CI_AS NULL,
	VhdType nvarchar(50) COLLATE Polish_CI_AS NULL,
	Size_GB float NULL,
	[Path] nvarchar(250) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_Hyper_V_HardDrives PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_NetAdapters definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_NetAdapters;

CREATE TABLE ChangeLog_Object_Hyper_V_NetAdapters (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	VMName nvarchar(50) COLLATE Polish_CI_AS NULL,
	SwitchName nvarchar(50) COLLATE Polish_CI_AS NULL,
	IsManagementOs bit NULL,
	MacAddress nvarchar(50) COLLATE Polish_CI_AS NULL,
	Status nvarchar(50) COLLATE Polish_CI_AS NULL,
	IPAddresses nvarchar(100) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_Hyper_V_NetAdapters PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_VMs definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Hyper_V_VMs;

CREATE TABLE ChangeLog_Object_Hyper_V_VMs (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	Name nvarchar(50) COLLATE Polish_CI_AS NULL,
	Generation int NULL,
	Version float NULL,
	OperationalStatus nvarchar(50) COLLATE Polish_CI_AS NULL,
	ProcessorCount int NULL,
	MemoryAssigned_GB float NULL,
	AutomaticStartAction nvarchar(50) COLLATE Polish_CI_AS NULL,
	AutomaticStopAction nvarchar(50) COLLATE Polish_CI_AS NULL,
	State nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_Hyper_V_VMs PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_NetworkAdapters definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_NetworkAdapters;

CREATE TABLE ChangeLog_Object_NetworkAdapters (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	Name nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	InterfaceDescription nvarchar(100) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	MacAddress nvarchar(20) COLLATE Polish_CI_AS NULL,
	LinkSpeed nvarchar(10) COLLATE Polish_CI_AS NULL,
	Status nvarchar(10) COLLATE Polish_CI_AS NULL,
	MediaType nvarchar(50) COLLATE Polish_CI_AS NULL,
	PhysicalMediaType nvarchar(50) COLLATE Polish_CI_AS NULL,
	VlanID int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_NetworkAdapters PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersDNSservers definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersDNSservers;

CREATE TABLE ChangeLog_Object_NetworkAdaptersDNSservers (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	DNSServer nvarchar(40) COLLATE Polish_CI_AS NULL,
	DNSServerOrder int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_NetworkAdaptersDNSservers PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersDefaultGateways definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersDefaultGateways;

CREATE TABLE ChangeLog_Object_NetworkAdaptersDefaultGateways (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	DestinationPrefix nvarchar(40) COLLATE Polish_CI_AS NULL,
	NextHop nvarchar(40) COLLATE Polish_CI_AS NULL,
	InterfaceMetric int NULL,
	RouteMetric int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_NetworkAdaptersDefaultGateways PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersIPaddresses definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_NetworkAdaptersIPaddresses;

CREATE TABLE ChangeLog_Object_NetworkAdaptersIPaddresses (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	IPAddress nvarchar(40) COLLATE Polish_CI_AS NULL,
	PrefixLength int NULL,
	AddressState nvarchar(20) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Object_NetworkAdaptersIPaddresses PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_OperatingSystem definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_OperatingSystem;

CREATE TABLE ChangeLog_Object_OperatingSystem (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NOT NULL,
	CurrentlyLoggedOn nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime2 NULL,
	OS_Version nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_Display_Version nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_build nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_Architecture nvarchar(50) COLLATE Polish_CI_AS NULL,
	isLicenseActivated nvarchar(50) COLLATE Polish_CI_AS NULL,
	Error nvarchar(1) COLLATE Polish_CI_AS NULL,
	FastStartEnabled bit NULL,
	LastBootTime datetime2 NULL,
	LastBootType nvarchar(50) COLLATE Polish_CI_AS NULL,
	CONSTRAINT PK_ChangeLog_OperatingSystem PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_Packages definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Packages;

CREATE TABLE ChangeLog_Object_Packages (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	DisplayName nvarchar(100) COLLATE Polish_CI_AS NULL,
	Publisher nvarchar(100) COLLATE Polish_CI_AS NULL,
	DisplayVersion nvarchar(100) COLLATE Polish_CI_AS NULL,
	InstallDate datetime2 NULL,
	InstallLocation nvarchar(250) COLLATE Polish_CI_AS NULL,
	QuietUninstallString nvarchar(250) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	EstimatedSize_GB float NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Packages PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.ChangeLog_Object_Partitions definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.ChangeLog_Object_Partitions;

CREATE TABLE ChangeLog_Object_Partitions (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	PartitionLetter nvarchar(10) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	Label nvarchar(50) COLLATE Polish_CI_AS NULL,
	FileSystem nvarchar(50) COLLATE Polish_CI_AS NULL,
	DriveCapacity_GB float NULL,
	DriveFreeSpace_GB float NULL,
	DriveUsed_Percentage float NULL,
	Automount bit NULL,
	Compressed bit NULL,
	BootVolume bit NULL,
	IndexingEnabled bit NULL,
	PageFilePresent bit NULL,
	QuotasEnabled bit NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(60) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_ChangeLog_Partitions PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.Event_AppErrors definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_AppErrors;

CREATE TABLE Event_AppErrors (
	TimeCreated datetime NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	Id int NULL,
	[Level] int NULL,
	ProviderName nvarchar(100) COLLATE Polish_CI_AS NULL,
	Message nvarchar(MAX) COLLATE Polish_CI_AS NULL,
	Row_ID nvarchar(120) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Event_AppErrors PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Event_Boots definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_Boots;

CREATE TABLE Event_Boots (
	[TimeStamp] datetime NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	BootType nvarchar(50) COLLATE Polish_CI_AS NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Event_Boots PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Event_Logons definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_Logons;

CREATE TABLE Event_Logons (
	[TimeStamp] datetime NULL,
	UserName nvarchar(50) COLLATE Polish_CI_AS NULL,
	[Domain] nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LogonType nvarchar(50) COLLATE Polish_CI_AS NULL,
	LogonProcess nvarchar(50) COLLATE Polish_CI_AS NULL,
	LogonSourceIP nvarchar(200) COLLATE Polish_CI_AS NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Event_Logons PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Event_PowerAndTemperature definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_PowerAndTemperature;

CREATE TABLE Event_PowerAndTemperature (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	[TimeStamp] datetime NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	CPU_Temperature_Current float NULL,
	CPU_Temperature_Min float NULL,
	CPU_Temperature_Max float NULL,
	PowerConsumption_Current float NULL,
	PowerConsumption_Min float NULL,
	PowerConsumption_Max float NULL,
	GPU_Temperature_Current float NULL,
	GPU_Temperature_Min float NULL,
	GPU_Temperature_Max float NULL,
	CONSTRAINT PK_PowerAndTemperature PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.Event_ResourceConsumption definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_ResourceConsumption;

CREATE TABLE Event_ResourceConsumption (
	ID uniqueidentifier DEFAULT newsequentialid() NOT NULL,
	[TimeStamp] datetime NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	CPU_Load_Percentage float NULL,
	RAM_Usage_Percentage float NULL,
	Disk_Time_Percentage float NULL,
	Disk_Read_MBps float NULL,
	Disk_Write_MBps float NULL,
	NIC_Sent_Mbps float NULL,
	NIC_Received_MBps float NULL,
	CONSTRAINT PK_ResourceConsumption PRIMARY KEY (ID)
);


-- Device_Monitoring.dbo.Event_SpeedTest definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Event_SpeedTest;

CREATE TABLE Event_SpeedTest (
	[TimeStamp] datetime NOT NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	Internal_IP nvarchar(40) COLLATE Polish_CI_AS NULL,
	MAC_Address nvarchar(20) COLLATE Polish_CI_AS NULL,
	Site_External_IP nvarchar(40) COLLATE Polish_CI_AS NULL,
	Site_ISP nvarchar(100) COLLATE Polish_CI_AS NULL,
	SpeedTest_Server_Name nvarchar(50) COLLATE Polish_CI_AS NULL,
	SpeedTest_Server_Hostname nvarchar(200) COLLATE Polish_CI_AS NULL,
	SpeedTest_Server_ID int NULL,
	SpeedTest_Server_IP nvarchar(40) COLLATE Polish_CI_AS NULL,
	SpeedTest_Server_Location nvarchar(50) COLLATE Polish_CI_AS NULL,
	SpeedTest_Server_Country nvarchar(50) COLLATE Polish_CI_AS NULL,
	PacketLoss_Percentage float NULL,
	Ping_Latency_ms float NULL,
	Ping_jitter_ms float NULL,
	Download_Speed_Mbps float NULL,
	Download_Latency_Low_ms float NULL,
	Download_Latency_High_ms float NULL,
	Upload_Speed_Mbps float NULL,
	Upload_Latency_Low_ms float NULL,
	Upload_Latency_High_ms float NULL,
	URL nvarchar(100) COLLATE Polish_CI_AS NULL,
	CONSTRAINT PK_Event_SpeedTest PRIMARY KEY ([TimeStamp])
);


-- Device_Monitoring.dbo.Inventory definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Inventory;

CREATE TABLE Inventory (
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NOT NULL,
	IPaddress nvarchar(50) COLLATE Polish_CI_AS NULL,
	isActiveWinRM bit NOT NULL,
	isActiveTCP bit NOT NULL,
	isActive bit NOT NULL,
	LastUpdate datetime2 NULL,
	LastSeen datetime2 NULL,
	RecentlyStarted bit NULL,
	IsHardwareMonitorDeployed bit NULL,
	MonitorHyper_V bit NULL,
	MonitorLogons bit NULL,
	Error nvarchar(MAX) COLLATE Polish_CI_AS NULL,
	CONSTRAINT PK_Inventory PRIMARY KEY (DNSHostName)
);


-- Device_Monitoring.dbo.Object_Hardware definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Hardware;

CREATE TABLE Object_Hardware (
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NOT NULL,
	LastUpdate datetime2 NULL,
	DeviceManufacturer nvarchar(50) COLLATE Polish_CI_AS NULL,
	DeviceModel nvarchar(50) COLLATE Polish_CI_AS NULL,
	NumberOfCPUs tinyint NULL,
	CPUmodel nvarchar(100) COLLATE Polish_CI_AS NULL,
	NumberOfCores tinyint NULL,
	NumberOfLogicalProcessors tinyint NULL,
	NumberOfRAMBanks tinyint NULL,
	RAMCapacity_GB tinyint NULL,
	RAMSpeed_MHz nvarchar(50) COLLATE Polish_CI_AS NULL,
	RAMmanufacturer nvarchar(50) COLLATE Polish_CI_AS NULL,
	GPU_Model nvarchar(100) COLLATE Polish_CI_AS NULL,
	DiskName nvarchar(100) COLLATE Polish_CI_AS NULL,
	StorageCapacity_GB smallint NULL,
	CONSTRAINT PK_Hardware PRIMARY KEY (DNSHostName)
);


-- Device_Monitoring.dbo.Object_Hyper_V_HardDrives definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Hyper_V_HardDrives;

CREATE TABLE Object_Hyper_V_HardDrives (
	VMName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ControllerType nvarchar(50) COLLATE Polish_CI_AS NULL,
	VhdFormat nvarchar(50) COLLATE Polish_CI_AS NULL,
	VhdType nvarchar(50) COLLATE Polish_CI_AS NULL,
	Size_GB float NULL,
	[Path] nvarchar(250) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_Hyper_V_HardDrives PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_Hyper_V_NetAdapters definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Hyper_V_NetAdapters;

CREATE TABLE Object_Hyper_V_NetAdapters (
	VMName nvarchar(50) COLLATE Polish_CI_AS NULL,
	SwitchName nvarchar(50) COLLATE Polish_CI_AS NULL,
	IsManagementOs bit NULL,
	MacAddress nvarchar(50) COLLATE Polish_CI_AS NULL,
	Status nvarchar(50) COLLATE Polish_CI_AS NULL,
	IPAddresses nvarchar(100) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_Hyper_V_NetAdapters PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_Hyper_V_VMs definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Hyper_V_VMs;

CREATE TABLE Object_Hyper_V_VMs (
	Name nvarchar(50) COLLATE Polish_CI_AS NULL,
	Generation int NULL,
	Version float NULL,
	OperationalStatus nvarchar(50) COLLATE Polish_CI_AS NULL,
	ProcessorCount int NULL,
	MemoryAssigned_GB float NULL,
	AutomaticStartAction nvarchar(50) COLLATE Polish_CI_AS NULL,
	AutomaticStopAction nvarchar(50) COLLATE Polish_CI_AS NULL,
	State nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_Hyper_V_VMs PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_NetworkAdapters definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_NetworkAdapters;

CREATE TABLE Object_NetworkAdapters (
	Name nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	InterfaceDescription nvarchar(100) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	MacAddress nvarchar(20) COLLATE Polish_CI_AS NULL,
	LinkSpeed nvarchar(10) COLLATE Polish_CI_AS NULL,
	Status nvarchar(10) COLLATE Polish_CI_AS NULL,
	MediaType nvarchar(50) COLLATE Polish_CI_AS NULL,
	PhysicalMediaType nvarchar(50) COLLATE Polish_CI_AS NULL,
	VlanID int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_NetworkAdapters PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_NetworkAdaptersDNSservers definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_NetworkAdaptersDNSservers;

CREATE TABLE Object_NetworkAdaptersDNSservers (
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	DNSServer nvarchar(40) COLLATE Polish_CI_AS NULL,
	DNSServerOrder int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_NetworkAdaptersDNSservers PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_NetworkAdaptersDefaultGateways definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_NetworkAdaptersDefaultGateways;

CREATE TABLE Object_NetworkAdaptersDefaultGateways (
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	DestinationPrefix nvarchar(40) COLLATE Polish_CI_AS NULL,
	NextHop nvarchar(40) COLLATE Polish_CI_AS NULL,
	InterfaceMetric int NULL,
	RouteMetric int NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_NetworkAdaptersDefaultGateways PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_NetworkAdaptersIPaddresses definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_NetworkAdaptersIPaddresses;

CREATE TABLE Object_NetworkAdaptersIPaddresses (
	InterfaceAlias nvarchar(50) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	ifIndex int NULL,
	AddressFamily nvarchar(5) COLLATE Polish_CI_AS NULL,
	IPAddress nvarchar(40) COLLATE Polish_CI_AS NULL,
	PrefixLength int NULL,
	AddressState nvarchar(20) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(100) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Object_NetworkAdaptersIPaddresses PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_OperatingSystem definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_OperatingSystem;

CREATE TABLE Object_OperatingSystem (
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NOT NULL,
	CurrentlyLoggedOn nvarchar(50) COLLATE Polish_CI_AS NULL,
	LastUpdate datetime2 NULL,
	OS_Version nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_Display_Version nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_build nvarchar(50) COLLATE Polish_CI_AS NULL,
	OS_Architecture nvarchar(50) COLLATE Polish_CI_AS NULL,
	isLicenseActivated nvarchar(50) COLLATE Polish_CI_AS NULL,
	Error nvarchar(1) COLLATE Polish_CI_AS NULL,
	FastStartEnabled bit NULL,
	LastBootTime datetime2 NULL,
	LastBootType nvarchar(50) COLLATE Polish_CI_AS NULL,
	CONSTRAINT PK_OperatingSystem PRIMARY KEY (DNSHostName)
);


-- Device_Monitoring.dbo.Object_Packages definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Packages;

CREATE TABLE Object_Packages (
	DisplayName nvarchar(100) COLLATE Polish_CI_AS NULL,
	Publisher nvarchar(100) COLLATE Polish_CI_AS NULL,
	DisplayVersion nvarchar(100) COLLATE Polish_CI_AS NULL,
	InstallDate datetime2 NULL,
	InstallLocation nvarchar(250) COLLATE Polish_CI_AS NULL,
	QuietUninstallString nvarchar(250) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	EstimatedSize_GB float NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(500) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Packages PRIMARY KEY (Row_ID)
);


-- Device_Monitoring.dbo.Object_Partitions definition

-- Drop table

-- DROP TABLE Device_Monitoring.dbo.Object_Partitions;

CREATE TABLE Object_Partitions (
	PartitionLetter nvarchar(10) COLLATE Polish_CI_AS NULL,
	DNSHostName nvarchar(50) COLLATE Polish_CI_AS NULL,
	Label nvarchar(50) COLLATE Polish_CI_AS NULL,
	FileSystem nvarchar(50) COLLATE Polish_CI_AS NULL,
	DriveCapacity_GB float NULL,
	DriveFreeSpace_GB float NULL,
	DriveUsed_Percentage float NULL,
	Automount bit NULL,
	BootVolume bit NULL,
	Compressed bit NULL,
	IndexingEnabled bit NULL,
	PageFilePresent bit NULL,
	QuotasEnabled bit NULL,
	LastUpdate datetime NULL,
	Row_ID nvarchar(60) COLLATE Polish_CI_AS NOT NULL,
	CONSTRAINT PK_Partitions PRIMARY KEY (Row_ID)
);